# Generated by Django 5.1.7 on 2025-03-24 17:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oredermodel',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(1, message='Цена не может быть 0')], verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='oredermodel',
            name='quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Количество должно быть положительным числом')], verbose_name='Количество'),
        ),
    ]
