# Generated by Django 5.1.7 on 2025-03-24 20:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_alter_oredermodel_price_alter_oredermodel_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oredermodel',
            name='total_price',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1, message='Общая стоимость должна быть положительным числом')], verbose_name='Стоимость заказа'),
        ),
    ]
