# Generated by Django 5.1.7 on 2025-03-31 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('my_app', '0003_alter_oredermodel_total_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('dish_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.oredermodel', verbose_name='Блюдо')),
            ],
        ),
    ]
