# Generated by Django 5.1.7 on 2025-04-11 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cart_options'),
        ('my_app', '0003_alter_oredermodel_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='dish_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.oredermodel', unique=True, verbose_name='Блюдо'),
        ),
    ]
